# Generated by Django 6.0.3 on 2026-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_delete_todoo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
