# Generated by Django 6.0.3 on 2026-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="srno",
        ),
        migrations.AddField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
